apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-issuance-app
  namespace: credit-card-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cc-issuance-app
  template:
    metadata:
      labels:
        app: cc-issuance-app
    spec:
      containers:
        - name: cc-issuance-app
          image: 2023cs03011/cc-issuance-service:1.0 # Use the image name you build
          imagePullPolicy: Always 
          ports:
            - containerPort: 5000
          env:
            - name: SQLALCHEMY_DATABASE_URI
              value: mysql://$(MYSQL_USER):$(MYSQL_PASSWORD)@mysql:3306/credit_cards_db
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: password
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: cc-issuance-app-rollout
  namespace: credit-card-app
spec:
  replicas: 1
  strategy:
    blueGreen:
      activeService: cc-issuance-app-service  # Stable service
      previewService: cc-issuance-app-service-preview  # New version preview
      autoPromotionEnabled: false  # Requires manual promotion
  selector:
    matchLabels:
      app: cc-issuance-app
  template:
    metadata:
      labels:
        app: cc-issuance-app
    spec:
      containers:
        - name: cc-issuance-app
          image: 2023cs03011/cc-issuance-service:latest  # Update image to trigger rollout
          imagePullPolicy: Always 
          ports:
            - containerPort: 5000
          env:
            - name: SQLALCHEMY_DATABASE_URI
              value: mysql://$(MYSQL_USER):$(MYSQL_PASSWORD)@mysql:3306/credit_cards_db
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: password
